version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST_PORT=0.0.0.0:8080
      - CACHE_SIZE=10
      - DEFAULT_CACHE_TTL=1m
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: curl --fail http://localhost:8081/api/ping || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
    restart: on-failure